### ISSUE TITLE
github.com/irisnet/core-sdk-go@v0.0.0-20210719031639-9c6ece68d908: invalid version: unknown revision 9c6ece68d908

### ISSUE THREAD

**Issue by pei55** [bianjieai/opb-sdk-go#12]
拷贝示例的代码，并修改了对应变量，然后go mod tidy的时候就报错：
go: github.com/irisnet/irismod-sdk-go/mt@v0.0.0-20220620094858-7fee6bda7414 requires
        github.com/irisnet/core-sdk-go@v0.0.0-20210719031639-9c6ece68d908: invalid version: unknown revision 9c6ece68d908
但我看go.mod里面，新的引用是github.com/irisnet/core-sdk-go v0.0.0-20220515104139-554292f91a1a
是不是mt里面没有更新go.mod？

**Comment by cyilong** [comment]
你好，可以使用 [v0.2.0-rc4](https://github.com/bianjieai/opb-sdk-go/tree/v0.2.0-rc4) 这个版本来解决这个问题的
