### ISSUE TITLE
CreateIdentityRequest 的id既然使用的uuid 为什么定义的是string，文档却写的byte

### ISSUE THREAD

**Issue by wxkj001** [bianjieai/opb-sdk-go#16]
CreateIdentityRequest 的id既然使用的uuid 为什么定义的是string，文档却写的byte

**Comment by cyilong** [comment]
你好，应该是文档还没有更新完成。Identity 的 ID 要求是十六进制字符，并且长度是 6 ~ 256 偶数个的字符。例如：48656c6c6f
